name: crop-care-env  
channels:
  - pytorch  # PyTorch channel for optimized builds
  - conda-forge  # conda-forge for broader package selection
dependencies:
  - python=3.8  
  - pip
  - transformers
  - datasets
  - pytorch=2.0.0  
  - matplotlib
  - evaluate
  - numpy
  - seaborn
  - tqdm
  - scikit-learn
  - torchvision

